name: record_linux
description: Stub for record_linux to fix build errors.
version: 0.7.2
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  record_platform_interface: ^1.5.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: RecordLinux
